### ISSUE TITLE
NearbyMonster Condition

### ISSUE THREAD

**Issue by sychotixdev** [sychotixdev/BuildYourOwnRoutine#1]
There is something screwy with the Nearby Monster Condition or multi-condition evaluation. Needs more investigation, so I'm opening up this issue as a reminder.

**Comment by madgentos** [comment]
as far as I understand does not work distance.
The trigger works when the monsters are shown on the mini map and not in the specified distance

**Comment by sychotixdev** [comment]
I went ahead and spent a few hours debugging this issue. I believe the issue was my use of ConcurrentBag for the list. I don't understand why... but sometimes the entities just were not being added back into the list.  I have commited the change to my current working branch (imgui_menu). This change will be merged into master whenever PoeHUD merges their imgui_menu branch into master.
