### ISSUE TITLE
Divination Distillate and mana Flask

### ISSUE THREAD

**Issue by ABORG87** [sychotixdev/BuildYourOwnRoutine#10]
i wanna use Divination Distillate and if my mana below 75% then my mana flask, but it seems not working, because if my Divination Distillate up then my mana flask not triggering himself if my mana below 75%.
pls tell me how to do that.
ty

**Comment by sychotixdev** [comment]
Do not use the flask type action if you are wanting to do special logic like that. The flask type action uses the buffs to determine if we are already using a type of potion (such as mana). In most cases, popping two mana flasks doesn't make sense. Honestly, popping the second mana flask might remove the divination distillate buff, but I'm not sure.

Also to be a little more clear, create the decorators as you want them, then use the UseFlaskAction with the flask index.

**Comment by ABORG87** [comment]
its not remove the divination distillate buff.
honestly im a littlebit noob with this, you can tell me clearer? :D

**Comment by ABORG87** [comment]
its not remove the divination distillate buff.
and i do that what you just suggested to me and its not working

**Comment by ABORG87** [comment]
ok somehow i did it but now the mana flask not have delay and its spammed like hell when my mana below 75% :D

**Comment by ABORG87** [comment]
sorry im noob with this you can help me out?

**Comment by ABORG87** [comment]
i find the timer,  (input, timeractionfactory, start timer, end timer)
but how i can add a delay exactly? like 4000ms before use it again

**Comment by ABORG87** [comment]
ah i find a timer where i can add ms, but not seems to working, :S

**Comment by sychotixdev** [comment]
Just to be sure, you may want to look at the buffs list through PoEHUD to ensure that the buff actually still effects you. The bar counting down on the flask is misleading. You could use the player has buff condition for the flask's item buff instead of a timer.

**Comment by ABORG87** [comment]
Divination Distillate has effect when i use it manualy with other mana flask (i check my item quantity)
what "player has buff" i need to choose? because the flask_effect_mana not working because the same reason.

**Comment by ABORG87** [comment]
ok i make a working one
invert the player has buff and choose that what my mana flask give me in my case: freez immunity

ty
