### ISSUE TITLE
Unique Flask conflict !

### ISSUE THREAD

**Issue by nndzung** [sychotixdev/BuildYourOwnRoutine#12]
Used FlaskBuff Condition slot 5 to maintain Zerphi's Last Breath (/w Righteous Fire). it's works.
But when I proc Divination Distillate (unique hybird HP/MP flask) manually , the FlaskBuff Condition above stop working.
Not related to mp flask , only flask buff condition on flask slot 5 :(

**Comment by sychotixdev** [comment]
As I said in the thread, FlaskBuff checks for the flask's main buff (such as mana or health) and not secondary buffs. Use the PlayerHasBuff condition instead for Zerphi's secondary buff.
