### ISSUE TITLE
Support for Warcry ( Battle Cry Talent)

### ISSUE THREAD

**Issue by totalschaden** [sychotixdev/BuildYourOwnRoutine#15]
Would be nice to see Support for Warcry (get Cooldown), not sure how to get around it so it wont spam while its on cd.

**Comment by sychotixdev** [comment]
Doesn't warcry put a buff on you? I think we already have a PlayerHasBuff condition that you can use. You can also use a timer if the buff expires before the skill is off cooldown.

**Comment by totalschaden** [comment]
Ok I did it with endurance changes duration now, getting the skill cd would still be neat.
Im wondering how to use one of two flask for the same action, do i have to add 2 Decorator for that ?
I lost the discord link to the poehud discord btw, do you have it ?

**Comment by sychotixdev** [comment]
Closing old resolved issue.
