### ISSUE TITLE
Delay [Resolved]

### ISSUE THREAD

**Issue by madgentos** [sychotixdev/BuildYourOwnRoutine#2]
Hello. Could you add a controlled delay for the trigger or action?
for reuse

**Comment by sychotixdev** [comment]
Controlled delay? Like... a new condition that will not return true until 5 seconds have passed for example?

**Comment by madgentos** [comment]
Aha
What to put on offer at 80% of life, and then spam a lot :)
And many thanks for what you are doing!

**Comment by sychotixdev** [comment]
If you are trying to use it for a flask... there is a canUseFlask condition I believe. If you are just trying to have it use a hotkey, then you are right... a delay condition would be useful. It shouldn't be hard to implement.

**Comment by madgentos** [comment]
yes for the key
little things but a lot of applications

**Comment by sychotixdev** [comment]
I don't think I will work on it tonight, but my current solution is probably going to be to add 1 condition and 1 action.

TimerCondition - Accepts a string and checks if a timer is completed or not with a configurable end time.
TimerAction - Accepts a string and begins/ends a timer.

With this solution, you would need to do something like this. Sound good?

Decorator(TimerCondition="Hotkey1Used")
{
    Sequence
    {
        UseHotkeyAction,
        TimerAction="Hotkey1Used", 5 seconds
    }
}

**Comment by madgentos** [comment]
good! 
urgency is not required :)
Thank you!

**Comment by sychotixdev** [comment]
Added TimerAction and TimerCondition in commit https://github.com/sychotixdev/BuildYourOwnRoutine/commit/bcaab6bbf629b8748c5954358b5f16593063468d

TimerAction starts or stops a timer. TimerCondition allows you a chance to perform actions based on how long the timer has been active. The example two comments up should work, but the "5 seconds" is configured on the condition, not the action.

Marking this issue as resolved unless issues are discovered.
