### ISSUE TITLE
MonsterHealthPercentThreshold doesn't work properly

### ISSUE THREAD

**Issue by opwj** [sychotixdev/BuildYourOwnRoutine#4]
There's a condition in file Extension/Default/Conditions/NearbyMonstersCondition.cs 
`if ((monsterLife.CurHP / monsterLife.MaxHP >= MonsterHealthPercentThreshold) == MonsterAboveHealthThreshold)`
that doesn't work properly. For example, when CurHP = 20, MaxHP = 100, then monsterLife.CurHP / monsterLife.MaxHP evaluates to 0.2, which is compared to integer 20.

**Comment by sychotixdev** [comment]
Good catch! I'll fix that up soon, or you can make a pull request

**Comment by sychotixdev** [comment]
Actually just had time to fix the issue since it was super easy. Commited, let me know if somehow it breaks something... as I didn't bother testing it.
