### ISSUE TITLE
May it support global reduced flask charges used?

### ISSUE THREAD

**Issue by yuwei111** [sychotixdev/BuildYourOwnRoutine#9]
There are two source of "global reduced flask charges used" in the game.
First is suffix from belts. the value is 10-20%.
Second is from passive skill tree, the value is 15%.
So the maximum value of "global reduced flask charges" is 35%. 
And the 35% is multiplicator with the local flask reduced flask charges used mod on the flasks.

The final charges per use will be : rounddown( rounddown(ChargesPerUse * (1-ChemistModValue)) * (1-reducedFlaskChargesUsed) ).

For example. Using a chemist's silver flask with 25% reduced charged used mod. and equipment a belt with 17% reduced flask charges used mod.
The tooltip of the flask will show "consumes 30 of 60 charges on use", and the hud support it.

But the real usage amount will be rounddown(30*0.83) = 24, this will cause some problem in some case.

**Comment by sychotixdev** [comment]
Did you notice a problem with this? There is already a some logic put in place to take into account the player stat for reduced charges and the flask mod for reduced charges. I would assume (more hope) that the player stat accounts for all of those other sources.

**Comment by sychotixdev** [comment]
Closing issue as this should be handled and OP has not responded in a while.
